import { StyleSheet } from 'react-native';

import { Color, Font, shadows } from '../../constants/GlobalStyle';

export const productDetailsStyle = StyleSheet.create({
  imageAndNavContainer: {
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.10)',
    backgroundColor: 'rgba(200, 59, 98, 0.06)',
    // backgroundColor: 'black',
  },
  navigationAndFavCon: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    width: '100%',
    height: 80,
    // paddingTop: 40,
    // backgroundColor: 'rgba(200, 59, 98, 0.06)',
    backgroundColor: Color.C_white,
  },
  favAndCartCon: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 80,
    justifyContent: 'space-between',
  },
  badge: {
    position: 'absolute',
    top: -12,
    right: -5,
    width: 20,
    height: 20,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Color.C_main,
  },
  badgeText: {
    color: Color.C_white,
  },
  navAndFav: {
    height: 34,
    width: 34,
    backgroundColor: '#fff',
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: Color.C_border,
    borderWidth: 1,
  },

  quantityAnimCon: {
    width: 20,
    height: 20,
    borderRadius: 20,
    backgroundColor: Color.C_main,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: -30,
    right: 110,
  },

  minusPlusText: {
    fontSize: Font.Font_XXL,
  },

  highLightedInfo: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 15,
    paddingHorizontal: 20,
    justifyContent: 'space-between',
    marginTop: 20,
    marginBottom: 40,
  },
  highLightedInfoItem: {
    width: '47.5%',
    height: 70,
    flexDirection: 'row',
    borderColor: Color.C_border,
    borderWidth: 1,
    borderRadius: 8,
    padding: 5,
    alignItems: 'center',
    paddingLeft: 15,
  },
  highLightedInfoItemLogoCon: {
    borderWidth: 1,
    borderColor: Color.C_border,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    height: 40,
    padding: 5,
    marginRight: 10,
  },
  highLightedInfoItemLogo: { width: '100%', height: '100%' },
  highLightedInfoItemName: {
    color: Color.C_H_black,
    fontSize: Font.Font_M,
    marginBottom: 5,
  },
  highLightedInfoItemSpec: { color: Color.C_black, fontSize: Font.Font_M },
  navigationContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderBottomColor: Color.C_border,
    borderBottomWidth: 1,
    marginHorizontal: 20,
  },
  activeNavigation: {
    borderBottomColor: Color.C_main,
    borderBottomWidth: 1,
    paddingBottom: 11,
    flex: 1,
    alignItems: 'center',
  },
  defaultNavigation: {
    flex: 1,
    alignItems: 'center',
  },
  BuyNowButtonAndAddToCartCon: {
    height: 130,
    position: 'absolute',
    bottom: 0,
    backgroundColor: Color.C_white,
    width: '100%',
    shadowColor: shadows.shadow_color,
    elevation: shadows.elevation_1,
    shadowOffset: {
      width: shadows.offsetWidth_1,
      height: shadows.offsetHeight_1,
    },
    shadowRadius: shadows.radius_1,
    shadowOpacity: shadows.opacity_1,
    alignItems: 'center',
  },
  offerPercentCon: {
    backgroundColor: '#F8F3FB',
    height: 35,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  buyButtonAndCartCon: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 15,
  },
  linearButton: {
    height: 50,
    width: '48%',
    alignSelf: 'flex-end',
    borderRadius: 30,
  },
  buyButton: {
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    width: '100%',
  },
  buttonText: {
    color: Color.C_white,
    fontSize: Font.Font_L,
  },
  cartButton: {
    borderRadius: 50,
    backgroundColor: '#FFF2F7',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginLeft: 10,
    width: '48%',
    height: 50,
    borderWidth: 1,
    borderColor: 'rgba(200, 59, 98, .1)',
  },
  addTorCartText: {
    fontSize: Font.Font_L,
    color: Color.C_black_eight,
    marginRight: 10,
  },
  // contentContainerStyle: {
  //   height: 280,
  //   width: '100%',
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },
  realatedProductCon: {
    marginBottom: 80,
    backgroundColor: Color.C_white,
    marginTop: 5,
    paddingBottom: 100,
  },
});
